#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
font_family                 FiraCode Nerd Font
font_size                   12
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
remember_window_size        no
initial_window_width        950
initial_window_height       500
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        5
hide_window_decorations     yes
background_opacity          0.6 
dynamic_background_opacity  yes 
confirm_os_window_close     1
selection_foreground        none
selection_background        none

cursor_shape beam
cursor_shape_unfocused hollow
cursor_trail 1
cursor                  #66b2ff
cursor_text_color       #000000

tab_bar_edge bottom
tab_bar_style fade
tab_bar_align center

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 10


allow_remote_control yes
allow_hyperlinks yes

foreground              #cecece
background              #000000

selection_foreground    #cecece
selection_background    #293334




#: URL underline color when hovering with mouse

url_color               #cd974b


#: The basic 16 colors

#: black
color0                  #000000
color8                  #777777

#: red
color1                  #e25d56
color9                  #f36868

#: green
color2                  #73ca50
color10                 #88db3f

#: yellow
color3                  #e9bf57
color11                 #f0bf7a

#: blue
color4                  #4a88e4
color12                 #6f8fdb

#: magenta
color5                  #915caf
color13                 #e987e9

#: cyan
color6                  #23acdd
color14                 #4ac9e2

#: white
color7                  #cecece
color15                 #ffffff


#: kitty window border colors and terminal bell colors

active_border_color             #777777
inactive_border_color           #323738
bell_border_color               #e97e57


#: Tab bar colors

active_tab_foreground           #f36868
active_tab_background           #242424
inactive_tab_foreground         #b8b8b8
inactive_tab_background         #323738










# include ./Tokyo Night.conf
