splash = false

wallpaper {
  monitor = eDP-1
  path = /home/adityaarch/Wallpapers/Spiderman Rain.png
  fit_mode = cover
}

wallpaper {
  monitor = eDP-2
  path = /home/adityaarch/Wallpapers/Spiderman Rain.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = /home/adityaarch/Wallpapers/Spiderman Rain.png
  fit_mode = cover
}
