-- Generated by nwg-displays on 2026-05-30 at 17:28:24. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1680x1050@144.0",
    position = "3724x2341",
    scale = 1.0,
    bitdepth = 10
})
hl.monitor({
    output = "huaweiTab",
    mode = "1280x800@60.0",
    position = "-1280x0",
    scale = 1.0
})
